version: '3.5'
services:
    web: 
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
        - '8080:8080'
        links:
        - mongo
    mongo:
        image: mongo
